[package]

name    = "raltc_mod_autocorrect"
version = "0.1.0"
edition = "2021"

[dependencies]

raltc_token = { path = "../../../raltc_token" }
raltc_path  = { path = "../../../raltc_path" }

raltc_mod_lexer = { path = "../raltc_mod_lexer" }
