[package]

name    = "raltc_tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]

raltc_script         = { path = "../raltc_script" }
raltc_tokens         = { path = "../raltc_tokens" }
raltc_language_error = { path = "../raltc_language_error" }
